// #4 Sowing the field:

import { addPlant } from "./field.js"
import { createAsparagus } from "./seeds/asparagus.js"
import { createCorn } from "./seeds/corn.js"
import { createPotato } from "./seeds/potato.js"
import { createSoybean } from "./seeds/soybean.js"
import { createSunflower } from "./seeds/sunflower.js"
import { createWheat } from "./seeds/wheat.js"

// In this module, define and export a plantSeeds function.
// The function must accept the year's planting plan as input (i.e. it must define a parameter).
// The plan is an array. It contains 4 arrays representing the rows in the field to be plants. Figure out how to iterate both the parent array and the child arrays.
// As you iterate the row of food types to be planted, invoke the corresponding factory function (e.g. if the food type is "Asparagus", invoke the createAsparagus function to get an asparagus seed).
// Take that seed and add it to the array of plants in the field module.




//For each array in the plantingPlan array iterate through the plant/seeds(soybeans, etc) then use an if statement to select the appropriate createSeed function (createSoybean, etc) and then use the addPlant function to add the plants/seeds to plantsArray from the field module.




export const plantSeeds = (plantingPlan) => {
    for (let row of plantingPlan) {  //loops through each of the 4 arrays (rows) in plantingPlan that represent the rows in the field 
        for (let toBePlanted of row) { //iterates through each individual plant in the row (soybean, asparagus, etc)
            //depending on the type of plant/seed, now we need to invoke the appropriate seed creating function (ex. createAsparagus, createSoybean, etc)
            if (toBePlanted === "Soybean") { // if the planting instruction is Soybean, invoke the createSoybean function and store it's result (the seed) in a variable...this generates the soybean seed for us.
                let seed = createSoybean()
                addPlant(seed) //addPlant adds the seed that was generated by createSoybean, and adds it to the field.
            }
            if (toBePlanted === "Corn") { // if the planting instruction is Corn, invoke the createCorn function and store it's result (the seed) in a variable...this generates the corn seed for us.
                let seed = createCorn()
                addPlant(seed) //addPlant adds the seed that was generated by createCorn, and adds it to the field.
            }
            if (toBePlanted === "Asparagus") { 
                let seed = createAsparagus()
                addPlant(seed) 
            }
            if (toBePlanted === "Potato") { 
                let seed = createPotato()
                addPlant(seed) 
            }
            if (toBePlanted === "Sunflower") { 
                let seed = createSunflower()
                addPlant(seed) //addPlant adds the seed that was generated by createSoybean, and adds it to the field.
            }
            if (toBePlanted === "Wheat") { 
                let seed = createWheat()
                addPlant(seed) //addPlant adds the seed that was generated by createSoybean, and adds it to the field.
            }

        }

    }
}


























